export type HypothesisStatus = "open" | "partial_close" | "closed";

export interface HypothesisData {
  ticker: string;
  company: string;
  sector: string;
  studyDate: string; // ISO date string
  priceAtStudy: number | null;
  status: HypothesisStatus;
  zoneValueLow: number | null;
  zoneValueHigh: number | null;
  zoneDeepLow: number | null;
  zoneDeepHigh: number | null;
  zoneHistLow: number | null;
  zoneHistHigh: number | null;
  scenarioNeg: number | null;
  scenarioBase: number | null;
  scenarioOpt: number | null;
  ratiosUsed: string[];
  htmlFile: string | null;
  closeNote?: string;
}

export const HYPOTHESES: HypothesisData[] = [
  {
    ticker: "AMD",
    company: "Advanced Micro Devices",
    sector: "Semiconductores",
    studyDate: "2025-02-01",
    priceAtStudy: 100,
    status: "partial_close",
    zoneValueLow: 95,
    zoneValueHigh: 105,
    zoneDeepLow: 80,
    zoneDeepHigh: 85,
    zoneHistLow: null,
    zoneHistHigh: null,
    scenarioNeg: null,
    scenarioBase: 155,
    scenarioOpt: null,
    ratiosUsed: ["P/E", "EV/EBITDA", "P/S"],
    htmlFile: "AMD_Caso_de_Estudio_20-Feb-2025.html",
    closeNote: "Cerrado parcial +145%",
  },
  {
    ticker: "NVO",
    company: "Novo Nordisk",
    sector: "Salud / Farmacéutica",
    studyDate: "2025-02-01",
    priceAtStudy: 80,
    status: "open",
    zoneValueLow: 77,
    zoneValueHigh: 83,
    zoneDeepLow: 67,
    zoneDeepHigh: 72,
    zoneHistLow: null,
    zoneHistHigh: null,
    scenarioNeg: null,
    scenarioBase: 116,
    scenarioOpt: null,
    ratiosUsed: ["P/E", "P/S", "FCF Yield"],
    htmlFile: "NVO_Caso_de_Estudio_20-Feb-2025.html",
  },
  {
    ticker: "BLD",
    company: "TopBuild Corp",
    sector: "Construcción",
    studyDate: "2025-02-01",
    priceAtStudy: 320,
    status: "closed",
    zoneValueLow: 310,
    zoneValueHigh: 330,
    zoneDeepLow: 255,
    zoneDeepHigh: 270,
    zoneHistLow: null,
    zoneHistHigh: null,
    scenarioNeg: null,
    scenarioBase: 410,
    scenarioOpt: null,
    ratiosUsed: ["P/E", "EV/EBITDA", "FCF Yield"],
    htmlFile: "BLD_Caso_de_Estudio_13-Feb-2025.html",
    closeNote: "Cerrado +50%",
  },
  {
    ticker: "ABNB",
    company: "Airbnb",
    sector: "Tecnología / Viajes",
    studyDate: "2025-04-01",
    priceAtStudy: 105,
    status: "open",
    zoneValueLow: 100,
    zoneValueHigh: 110,
    zoneDeepLow: 80,
    zoneDeepHigh: 90,
    zoneHistLow: null,
    zoneHistHigh: null,
    scenarioNeg: null,
    scenarioBase: 130,
    scenarioOpt: null,
    ratiosUsed: ["P/E", "FCF Yield", "P/S"],
    htmlFile: "ABNB_Caso_de_Estudio_10-Abr-2025.html",
  },
  {
    ticker: "ASML",
    company: "ASML Holding",
    sector: "Semiconductores",
    studyDate: "2025-04-01",
    priceAtStudy: 625,
    status: "partial_close",
    zoneValueLow: 600,
    zoneValueHigh: 650,
    zoneDeepLow: 500,
    zoneDeepHigh: 550,
    zoneHistLow: null,
    zoneHistHigh: null,
    scenarioNeg: null,
    scenarioBase: 850,
    scenarioOpt: null,
    ratiosUsed: ["P/E", "EV/EBITDA", "P/S"],
    htmlFile: "ASML_Caso_de_Estudio_11-Abr-2025.html",
    closeNote: "Cierre parcial +78%",
  },
  {
    ticker: "UNH",
    company: "UnitedHealth Group",
    sector: "Salud / Seguros",
    studyDate: "2025-05-01",
    priceAtStudy: 290,
    status: "open",
    zoneValueLow: 280,
    zoneValueHigh: 300,
    zoneDeepLow: 245,
    zoneDeepHigh: 265,
    zoneHistLow: null,
    zoneHistHigh: null,
    scenarioNeg: null,
    scenarioBase: 400,
    scenarioOpt: null,
    ratiosUsed: ["P/E", "P/S", "EV/EBITDA"],
    htmlFile: "UNH_Caso_de_Estudio_14-May-2025.html",
  },
  {
    ticker: "MC",
    company: "LVMH Moët Hennessy",
    sector: "Lujo",
    studyDate: "2025-05-01",
    priceAtStudy: 467,
    status: "open",
    zoneValueLow: 450,
    zoneValueHigh: 485,
    zoneDeepLow: 400,
    zoneDeepHigh: 420,
    zoneHistLow: null,
    zoneHistHigh: null,
    scenarioNeg: null,
    scenarioBase: null,
    scenarioOpt: null,
    ratiosUsed: ["P/E", "EV/EBITDA"],
    htmlFile: "MC_Caso_de_Estudio_27-May-2025.html",
  },
  {
    ticker: "DLO",
    company: "DLocal",
    sector: "Fintech / Pagos",
    studyDate: "2025-07-01",
    priceAtStudy: 10.5,
    status: "open",
    zoneValueLow: 10,
    zoneValueHigh: 11,
    zoneDeepLow: null,
    zoneDeepHigh: null,
    zoneHistLow: null,
    zoneHistHigh: null,
    scenarioNeg: null,
    scenarioBase: 16,
    scenarioOpt: null,
    ratiosUsed: ["P/E", "FCF Yield", "P/S"],
    htmlFile: "DLO_Caso_de_Estudio_17-Jul-2025.html",
  },
  {
    ticker: "ADBE",
    company: "Adobe Inc.",
    sector: "Tecnología / Software",
    studyDate: "2025-09-01",
    priceAtStudy: 345,
    status: "open",
    zoneValueLow: 335,
    zoneValueHigh: 355,
    zoneDeepLow: 300,
    zoneDeepHigh: 310,
    zoneHistLow: null,
    zoneHistHigh: null,
    scenarioNeg: null,
    scenarioBase: 540,
    scenarioOpt: null,
    ratiosUsed: ["P/E", "FCF Yield", "P/S", "EV/EBITDA"],
    htmlFile: "ADBE_Caso_de_Estudio_16-Sep-2025.html",
  },
  {
    ticker: "CMG",
    company: "Chipotle Mexican Grill",
    sector: "Restaurantes",
    studyDate: "2025-10-01",
    priceAtStudy: 38.5,
    status: "open",
    zoneValueLow: 37,
    zoneValueHigh: 40,
    zoneDeepLow: 32,
    zoneDeepHigh: 35,
    zoneHistLow: null,
    zoneHistHigh: null,
    scenarioNeg: null,
    scenarioBase: 55,
    scenarioOpt: null,
    ratiosUsed: ["P/E", "EV/EBITDA", "FCF Yield"],
    htmlFile: "CMG_Caso_de_Estudio_02-Oct-2025.html",
  },
  {
    ticker: "DECK",
    company: "Deckers Outdoor",
    sector: "Consumo / Calzado",
    studyDate: "2025-11-01",
    priceAtStudy: 80.5,
    status: "open",
    zoneValueLow: 79,
    zoneValueHigh: 82,
    zoneDeepLow: 70,
    zoneDeepHigh: 74,
    zoneHistLow: null,
    zoneHistHigh: null,
    scenarioNeg: null,
    scenarioBase: 125,
    scenarioOpt: null,
    ratiosUsed: ["P/E", "FCF Yield", "EV/EBITDA"],
    htmlFile: "DECK_Caso_de_Estudio_10-Nov-2025.html",
  },
  {
    ticker: "DUOL",
    company: "Duolingo",
    sector: "Tecnología / Educación",
    studyDate: "2026-01-01",
    priceAtStudy: 185,
    status: "open",
    zoneValueLow: 180,
    zoneValueHigh: 190,
    zoneDeepLow: 150,
    zoneDeepHigh: 160,
    zoneHistLow: null,
    zoneHistHigh: null,
    scenarioNeg: null,
    scenarioBase: 260,
    scenarioOpt: null,
    ratiosUsed: ["P/S", "EV/EBITDA"],
    htmlFile: "DUOL_Caso_de_Estudio_05-Ene-2026.html",
  },
  {
    ticker: "DVA",
    company: "DaVita Inc.",
    sector: "Salud / Diálisis",
    studyDate: "2026-01-01",
    priceAtStudy: 103,
    status: "partial_close",
    zoneValueLow: 100,
    zoneValueHigh: 106,
    zoneDeepLow: 75,
    zoneDeepHigh: 85,
    zoneHistLow: null,
    zoneHistHigh: null,
    scenarioNeg: null,
    scenarioBase: 150,
    scenarioOpt: null,
    ratiosUsed: ["P/E", "EV/EBITDA", "FCF Yield"],
    htmlFile: "DVA_Caso_de_Estudio_15-Ene-2026.html",
    closeNote: "Cerrado parcial +78%",
  },
  {
    ticker: "INTU",
    company: "Intuit Inc.",
    sector: "Tecnología / Software Financiero",
    studyDate: "2026-03-01",
    priceAtStudy: 365,
    status: "open",
    zoneValueLow: 360,
    zoneValueHigh: 370,
    zoneDeepLow: 330,
    zoneDeepHigh: 340,
    zoneHistLow: null,
    zoneHistHigh: null,
    scenarioNeg: null,
    scenarioBase: 520,
    scenarioOpt: null,
    ratiosUsed: ["P/E", "FCF Yield", "EV/EBITDA"],
    htmlFile: "INTU_Caso_de_Estudio_05-Mar-2026.html",
  },
  {
    ticker: "MSFT",
    company: "Microsoft Corporation",
    sector: "Tecnología",
    studyDate: "2026-04-01",
    priceAtStudy: 360,
    status: "open",
    zoneValueLow: 350,
    zoneValueHigh: 370,
    zoneDeepLow: 300,
    zoneDeepHigh: 315,
    zoneHistLow: null,
    zoneHistHigh: null,
    scenarioNeg: null,
    scenarioBase: 480,
    scenarioOpt: null,
    ratiosUsed: ["P/E", "FCF Yield", "P/S", "EV/EBITDA"],
    htmlFile: "MSFT_Caso_de_Estudio_06-Abr-2026.html",
  },
  {
    ticker: "DPZ",
    company: "Domino's Pizza",
    sector: "Restaurantes",
    studyDate: "2026-04-01",
    priceAtStudy: 357.5,
    status: "open",
    zoneValueLow: 345,
    zoneValueHigh: 370,
    zoneDeepLow: 290,
    zoneDeepHigh: 305,
    zoneHistLow: null,
    zoneHistHigh: null,
    scenarioNeg: null,
    scenarioBase: 510,
    scenarioOpt: null,
    ratiosUsed: ["P/E", "FCF Yield", "EV/EBITDA"],
    htmlFile: "DPZ_Caso_de_Estudio_20-Feb-2025.html",
  },
  {
    ticker: "VEEV",
    company: "Veeva Systems",
    sector: "Tecnología / Healthcare SaaS",
    studyDate: "2026-05-06",
    priceAtStudy: 165,
    status: "open",
    zoneValueLow: 160,
    zoneValueHigh: 170,
    zoneDeepLow: 130,
    zoneDeepHigh: 140,
    zoneHistLow: null,
    zoneHistHigh: null,
    scenarioNeg: null,
    scenarioBase: 245,
    scenarioOpt: null,
    ratiosUsed: ["P/E", "FCF Yield", "P/S", "EV/EBITDA"],
    htmlFile: "VEEV_Caso_de_Estudio_06-May-2026.html",
  },
];

export function getHypothesis(ticker: string): HypothesisData | undefined {
  return HYPOTHESES.find((h) => h.ticker === ticker);
}
